name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-18.04 ]
        java: [ 11, 17, 19, 20, 21, 22, 23-ea ]
      fail-fast: false
      max-parallel: 4
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: v1-dependencies-{{ checksum "project.clj" }}
        restore-keys: |
          v1-dependencies-{{ checksum "project.clj" }}
    - name: Install dependencies
      run: lein deps
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: v1-dependencies-{{ checksum "project.clj" }}
    - name: Run tests
      run: lein test
